
export async function GET() {
  throw new Error('Error intencional para probar el manejo global de errores'); // Genera un error
}
